import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./{Components}/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="w-full h-full flex flex-col m-0 p-0 font-[Relance]">
          <Navbar />
        {children}
      </body>
    </html>
  );
}
